ai_providers:
  anthropic:
    api_key: ''
    max_tokens: 2000
    model: claude-3-opus-20240229
    temperature: 0.7
  custom:
    headers:
      Authorization: ''
    model_param_name: model
    prompt_param_name: prompt
    response_path: choices[0].text
    url: ''
  default_provider: openai
  dev_mode: true
  llama:
    api_key: ''
    max_tokens: 2000
    model: llama-3-70b-instruct
    temperature: 0.7
  openai:
    api_key: ''
    max_tokens: 2000
    model: gpt-4-turbo-preview
    temperature: 0.7
  stability:
    api_key: ''
    cfg_scale: 7.0
    engine: stable-diffusion-xl-1024-v1-0
    height: 1024
    steps: 30
    width: 1024
audio:
  add_noise_reduction: true
  background_music: true
  music_volume: 0.2
  normalize_audio: true
content_generation:
  auto_enhance_scripts: true
  auto_generate_visuals: true
  cache:
    enabled: true
    max_size_mb: 1000
    ttl_days: 7
  script:
    max_length: 2000
    tone_options:
    - professional
    - casual
    - enthusiastic
    - serious
    - friendly
    - informative
    - entertaining
    - educational
  visual_prompts:
    auto_generate: true
    detail_level: high
    style_match: true
export:
  export_settings:
    format: mp4
    resolution: 1080p
media:
  bitrate: 5000k
  fps: 30
  imagemagick:
    path: magick
  mode: auto
  quality: high
  resolution:
    height: 1080
    width: 1920
niches:
  fitness:
    script_template: templates/fitness_script.yaml
    style: motivational
  politics:
    script_template: templates/politics_script.yaml
    style: assertive
  tech:
    script_template: templates/tech_script.yaml
    style: neutral
performance:
  export-settings:
    resolution: 1080p
  parallel_processing: true
  preview_quality: medium
  template-selection:
    tech: true
  threads: 4
  use_gpu: false
  voice-selection:
    ElevenLabs: true
project:
  cache_dir: ./cache/
  default_niche: tech
  default_tone: serious
  log_dir: ./logs/
  name: AutomationProject
  output_dir: ./Output_Manager/outputs/
  output_directory: output
  temp_dir: ./temp/
scene:
  auto_timing: true
  default_duration: 5
  intro:
    duration: 3.0
    enabled: false
    text: Presents
  max_duration: 15
  min_duration: 3
  outro:
    duration: 5.0
    enabled: false
    include_credits: true
    text: Thanks for watching
  overlay_text: true
  random_transitions: false
  transition_types:
  - fade
  - slide
  - none
sources:
  cache:
    enabled: true
    expiry_days: 7
    max_size_mb: 1000
  local:
    enabled: true
    paths:
      audio: ./Content_Engine/assets/audio/
      fonts: ./Content_Engine/assets/fonts/
      images: ./Content_Engine/assets/images/
      videos: ./Content_Engine/assets/videos/
  pexels:
    api_key: YOUR_PEXELS_API_KEY
    enabled: false
    orientation: landscape
    size: large
  pixabay:
    api_key: REPLACE_WITH_YOUR_PIXABAY_API_KEY
    category: ''
    enabled: true
    image_type: photo
    min_height: 1080
    min_width: 1920
    orientation: horizontal
    safesearch: true
  unsplash:
    api_key: YOUR_UNSPLASH_API_KEY
    enabled: false
    orientation: landscape
template:
  niche_templates:
  - product_demo
  - explainer
text_processing:
  content_filtering: true
  keyword_extraction: true
  keyword_limit: 5
  language_detection: true
  sentiment_analysis: true
tts:
  language: ur
  speed: 1.0
video:
  debug_mode: true
  output_dir: output_manager/videos
  resolution: FHD
  style_name: modern
video_export:
  format: mp4
  fps: 30
  resolution: 1920x1080
video_style:
  animation_style: subtle
  background_blur: 5
  background_color: '#ADD8E6'
  color_correction:
    brightness: 0
    contrast: 0
    enabled: false
    saturation: 0
  enable_animations: false
  font: Arial
  font_color: white
  font_size: 100
  stroke_color: black
  stroke_width: 2
  text_effect: typewriter
  text_opacity: 0.9
  text_position: center
  transition: slide
  transition_duration: 1.0
  watermark:
    enabled: false
    image_path: ./Content_Engine/assets/branding/logo.png
    opacity: 0.7
    position: bottom-right
  zoom_effect: false
  zoom_ratio: 0.05
voice:
  elevenlabs:
    api_key: ''
    voice_id: ''
  local:
    voice_name: Default
  provider: local
  tone_preferences:
  - serious
  - funny
  - educational
