# Video Generation System Configuration

# Project Settings
project:
  name: "Auto Video Generator"
  output_dir: "./Output_Manager/outputs/"
  temp_dir: "./temp/"
  log_dir: "./logs/"

# Media Settings
media:
  mode: "auto"  # Options: "auto", "manual"
  resolution:
    width: 1920
    height: 1080
  fps: 30

# Media Sources Configuration
sources:
  # Pixabay API Configuration
  pixabay:
    enabled: true
    api_key: "YOUR_PIXABAY_API_KEY"
    image_type: "photo"  # Options: "all", "photo", "illustration", "vector"
    orientation: "horizontal"  # Options: "all", "horizontal", "vertical"
    category: ""  # Leave empty for all categories
    min_width: 1920
    min_height: 1080

  # Pexels API Configuration
  pexels:
    enabled: false
    api_key: "YOUR_PEXELS_API_KEY"
    orientation: "landscape"  # Options: "landscape", "portrait", "square"
    size: "large"  # Options: "large", "medium", "small"

  # Unsplash API Configuration
  unsplash:
    enabled: false
    api_key: "YOUR_UNSPLASH_API_KEY"
    orientation: "landscape"  # Options: "landscape", "portrait", "squarish"

  # Local Assets Configuration
  local:
    enabled: true
    paths:
      images: "./Content_Engine/assets/images/"
      videos: "./Content_Engine/assets/videos/"
      fonts: "./Content_Engine/assets/fonts/"
      audio: "./Content_Engine/assets/audio/"

# Text-to-Speech Configuration
tts:
  provider: "google"  # Options: "google", "amazon", "local"
  language: "en-US"
  voice: "en-US-Standard-D"
  speed: 1.0
  # Google TTS specific settings
  google:
    api_key: "YOUR_GOOGLE_TTS_API_KEY"
  # Amazon Polly specific settings
  amazon:
    region: "us-east-1"
    access_key: "YOUR_AWS_ACCESS_KEY"
    secret_key: "YOUR_AWS_SECRET_KEY"

# Text Processing Settings
text_processing:
  keyword_extraction: true
  keyword_limit: 5
  sentiment_analysis: true

# Video Style Settings
video_style:
  font: "Arial"
  font_size: 70
  font_color: "white"
  text_position: "center"  # Options: "center", "bottom", "top"
  background_color: "#000000"  # Used if no background image
  transition: "fade"  # Options: "fade", "slide", "none"
  transition_duration: 1.0  # In seconds

# Scene Settings
scene:
  default_duration: 5  # In seconds
  min_duration: 3  # In seconds
  max_duration: 10  # In seconds
  auto_timing: true  # Automatically adjust scene duration based on text length